name: Rust-geph4

on:
  watch:
     types: [started]
  pull_request:
    branches: [ https://github.com/geph-official/geph4.git ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /geph4
        sudo chown $USER:$GROUPS /geph4
        curl -sSL https://get.docker.com/ | sudo sh
        cargo install cross
        export PATH=~/.cargo/bin:$PATH
    - name: Build
      run: |
      cd geph4/
      cross build --release --locked --target armv7-linux-androideabi --manifest-path=geph4-client/Cargo.toml
      cross build --release --locked --target aarch64-linux-android --manifest-path=geph4-client/Cargo.toml
      mkdir OUTPUT
      mv target/armv7-linux-androideabi/release/geph4-client OUTPUT/geph4-client-android-armv7
      mv target/aarch64-linux-android/release/geph4-client OUTPUT/geph4-client-android-aarch64

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        path: geph4/OUTPUT
